[/Script/Engine.InputSettings]
; Legacy input (UE4). Keyboard/mouse and gamepad.
+AxisMappings=(AxisName="MoveForward",Scale=1.000000,Key=W)
+AxisMappings=(AxisName="MoveForward",Scale=-1.000000,Key=S)
+AxisMappings=(AxisName="MoveForward",Scale=1.000000,Key=Gamepad_LeftY)
+AxisMappings=(AxisName="MoveRight",Scale=1.000000,Key=D)
+AxisMappings=(AxisName="MoveRight",Scale=-1.000000,Key=A)
+AxisMappings=(AxisName="MoveRight",Scale=1.000000,Key=Gamepad_LeftX)
+AxisMappings=(AxisName="Turn",Scale=1.000000,Key=MouseX)
+AxisMappings=(AxisName="LookUp",Scale=-1.000000,Key=MouseY)
+AxisMappings=(AxisName="TurnRate",Scale=1.000000,Key=Gamepad_RightX)
+AxisMappings=(AxisName="LookUpRate",Scale=-1.000000,Key=Gamepad_RightY)
+ActionMappings=(ActionName="Jump",Key=SpaceBar)
+ActionMappings=(ActionName="Jump",Key=Gamepad_FaceButton_Bottom)
+ActionMappings=(ActionName="CastSpell",Key=LeftMouseButton)
+ActionMappings=(ActionName="CastSpell",Key=Gamepad_RightTrigger)
+ActionMappings=(ActionName="Melee",Key=RightMouseButton)
+ActionMappings=(ActionName="Melee",Key=F)
+ActionMappings=(ActionName="Melee",Key=Gamepad_FaceButton_Left)
+ActionMappings=(ActionName="Interact",Key=E)
+ActionMappings=(ActionName="Interact",Key=Gamepad_FaceButton_Right)
+ActionMappings=(ActionName="NextSpell",Key=MouseScrollUp)
+ActionMappings=(ActionName="NextSpell",Key=Q)
+ActionMappings=(ActionName="NextSpell",Key=Gamepad_RightShoulder)
+ActionMappings=(ActionName="PrevSpell",Key=MouseScrollDown)
+ActionMappings=(ActionName="PrevSpell",Key=Gamepad_LeftShoulder)
+ActionMappings=(ActionName="RallyFollowers",Key=R)
+ActionMappings=(ActionName="RallyFollowers",Key=Gamepad_FaceButton_Top)
+ActionMappings=(ActionName="ToggleDebug",Key=F3)
